version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: drawing_app_postgres
    restart: always
    environment:
      POSTGRES_DB: drawing_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: